sudo: true
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

env:
  - DB=mysql


before_script:
    #- curl -sS https://getcomposer.org/installer | php; sudo mv composer.phar /usr/local/bin/composer
    #- composer install
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hackademic;" -uroot; fi
  - if [[ "$DB" == "mysql"]]; then mysql -e "hackademic < installation/sql/db.sql" -uroot; fi

script:
    #  - phpunit --configuration phpunit_mysql.xml --coverage-text
  - vendor/bin/phpunit --configuration phpunit_mysql.xml --coverage-html ./report hackademic_devtests/successTest.php

install:
 - composer install

notifications:
  irc:
    channels: "irc.freenode.org#hackademic-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false

after_success:
  coveralls --rcfile=.coveragerc
