sudo: true
language: php
php:
  # aliased to 5.2.17
  - 5.2
  # aliased to 5.3.29
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  - hhvm
  - nightly

env:
  - DB=mysql


before_script:
  - curl -sS https://getcomposer.org/installer | php; sudo mv composer.phar /usr/local/bin/composer
  - php composer.phar install
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hackademic;" -uroot; fi

script:
  - phpunit --configuration phpunit_mysql.xml --coverage-text

#install:
# - php composer.phar install

notifications:
  irc:
    channels: "irc.freenode.org#hackademic-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
    use_notice: true
  email: false

after_success:
  coveralls --rcfile=.coveragerc
